version: "3"
services:
  terraform:
    image: hashicorp/terraform:1.3.7
    env_file:
      - ./.env
    volumes:
      -  ./terraform:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "yarn start"
    ports:
      -  "3000:3000"